# -*- coding: utf-8 -*-
"""Assignment-1_21IM10008.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HZ4YH8ZGga55_BjoqPYfJg5NE9uHsY1w

***Name- Aritra Ray***

***Roll No.- 21IM10008***
"""

#importing the packages
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

"""#Experiment 1"""

#Loading the data set and creating the dataframe
data_csv=pd.read_csv('sales_data.csv')
df=pd.DataFrame(data_csv)

df.head(8)

"""#Experiment 2"""

#Printed the dataframe using .isna() func to check null
missing_val=df.isnull()
print(missing_val)
#Replaced with the mean value of the respective group.
missing_val=missing_val.sum()
cols_missing_val = missing_val[missing_val > 0].index.tolist()
for col in cols_missing_val:
  df[col].fillna(df[col].mean(),inplace=True)
df

"""#Experiment 3"""

#With the results of Experiment 2, created a line plot to visualize the revenue trend over date
df['Revenue']=df['Price']*df['Quantity']
plt.plot(df['Date'],df['Revenue'], marker='o', linestyle='-')
plt.xticks(rotation=45)
plt.title('Revenue trend over date', fontsize = 15)
plt.xlabel('Date')
plt.ylabel('Revenue')
plt.show()

"""#Experiment 4"""

cnt=0
for i in df['OrderID']:
  cnt+=1
print("The total number of Orders ",cnt)
revenue=df['Revenue'].sum()
print("The total revenue generated from the sales ",revenue)

"""#Experiment 5"""

#Calculating avg-price & top most sold product
unique_pdt=df['Product'].unique()
dict_price={}
dict_quantity={}
avg_price={}
for i in unique_pdt:
  dict_price[i]=0
  dict_quantity[i]=0
  avg_price[i]=0
for index, row in df.iterrows():
    product = row['Product']
    price = row['Price']
    quant= row['Quantity']
    dict_price[product] += price
    dict_quantity[product]+=quant
    avg_price[product]=dict_price[product]/dict_quantity[product]
max_sold_pdt=max(dict_quantity)
print("Average price of each product ",avg_price)
print("The top most sold product ",max_sold_pdt)
#Bar plot to visualize the average price of the product
products=list(avg_price.keys())
avgPrices=list(avg_price.values())
plt.bar(products,avgPrices)
plt.xlabel("Product Type")
plt.ylabel("Average Price")
plt.title("bar plot to visualize the average price of the product")
plt.show()